### ISSUE TITLE
No handler was subscribed to command

### ISSUE THREAD

**Issue by vbaidak** [AxonFramework/cdi#29]
Hi!

I'm trying to test [example application](https://github.com/AxonFramework/cdi/tree/master/example/javaee) running on JBOSS EAP 7.1 and getting the following stacktrace:

```
org.axonframework.commandhandling.NoHandlerForCommandException: No handler was subscribed to command [java.util.LinkedHashMap]
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:422)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.axonframework.commandhandling.NoHandlerForCommandException: No handler was subscribed to command [java.util.LinkedHashMap]
	at org.axonframework.commandhandling.SimpleCommandBus.lambda$doDispatch$0(SimpleCommandBus.java:116)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.axonframework.commandhandling.SimpleCommandBus.doDispatch(SimpleCommandBus.java:114)
	at org.axonframework.commandhandling.SimpleCommandBus.dispatch(SimpleCommandBus.java:85)
	at org.axonframework.commandhandling.gateway.AbstractCommandGateway.send(AbstractCommandGateway.java:79)
	at org.axonframework.commandhandling.gateway.DefaultCommandGateway.send(DefaultCommandGateway.java:95)
	at org.axonframework.commandhandling.gateway.DefaultCommandGateway.send(DefaultCommandGateway.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.axonframework.commandhandling.gateway.CommandGateway$71779371$Proxy$_$$_WeldClientProxy.send(Unknown Source)
	at ch.mobi.apsbau.axonintegration.infrastructure.resource.UserResource.command(UserResource.java:27)
	at ch.mobi.apsbau.axonintegration.infrastructure.resource.UserResource$Proxy$_$$_WeldClientProxy.command(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
	... 44 more
```

**Comment by vbaidak** [comment]
It seems this is true not only for commands, but also for events and sagas.
The issues is that, **PayloadParameterResolver** is missing during method member initialization. 
Instead, we have **CdiParameterResolver**

**Comment by vbaidak** [comment]
I was able to fix the issue by "overriding" **org.axonframework.messaging.annotation.ParameterResolverFactory** service with the following content:
```
org.axonframework.commandhandling.CurrentUnitOfWorkParameterResolverFactory
org.axonframework.commandhandling.conflictresolution.ConflictResolution
org.axonframework.eventhandling.TimestampParameterResolverFactory
org.axonframework.eventhandling.ConcludesBatchParameterResolverFactory
org.axonframework.eventsourcing.SequenceNumberParameterResolverFactory
org.axonframework.eventsourcing.eventstore.TrackingTokenParameterResolverFactory
org.axonframework.messaging.annotation.DefaultParameterResolverFactory
org.axonframework.messaging.annotation.MessageIdentifierParameterResolverFactory
org.axonframework.eventhandling.replay.ReplayParameterResolverFactory
org.axonframework.commandhandling.InterceptorChainParameterResolverFactory
org.axonframework.cdi.messaging.annotation.CdiParameterResolverFactory
```

where the last line, **org.axonframework.cdi.messaging.annotation.CdiParameterResolverFactory** is actually a **ParameterResolverFactory** from the cdi extension library, and all the preceding lines are from **axon-core** library

**Comment by bert-laverman** [comment]
Vladyslav,
I just checked out a fresh copy of the CDI example, branch "4.0.x", and apart from a small mistake in the persistence.xml (it tries to map the abstract base classes, but you can simply remove them) it runs without problems on JBOSS EAP 7.2 and WildFly 14.0.1.

For your reference, my persistence.xml now looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1"
             xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
                           http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
  <persistence-unit name="accounts">
    <!-- TODO Eliminate this using provider-specific programmatic
        registration APIs. This will confuse most users. -->
    <!-- TODO Double-check that this is a complete list -->

    <class>org.axonframework.eventsourcing.eventstore.jpa.DomainEventEntry</class>
    <class>org.axonframework.eventsourcing.eventstore.jpa.SnapshotEventEntry</class>
    <class>org.axonframework.eventhandling.tokenstore.jpa.TokenEntry</class>
    <class>org.axonframework.modelling.saga.repository.jpa.AssociationValueEntry</class>
    <class>org.axonframework.modelling.saga.repository.jpa.SagaEntry</class>
    <properties>
      <property name="jboss.entity.manager.jndi.name" value="java:/accounts"/>

      <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
      <property name="openjpa.jdbc.SynchronizeMappings" value="buildSchema"/>
      <property name="eclipselink.logging.level.sql" value="FINE"/>
      <property name="eclipselink.logging.parameters" value="true"/>
      <property name="hibernate.show_sql" value="true"/>
    </properties>
  </persistence-unit>
</persistence>
```

**Comment by bert-laverman** [comment]
I pushed this small update to the 4.0.x branch.

**Comment by vbaidak** [comment]
Hi @bert-laverman ! Thanks for checking this out and sorry for late response.

It could be the case that [**Priority**](https://github.com/AxonFramework/AxonFramework/blob/31fe8a7eae7bf019b7e7e4fc10d5ee2230e0b56b/messaging/src/main/java/org/axonframework/common/Priority.java) does matter.
I see that [**CdiParameterResolverFactory**](https://github.com/AxonFramework/cdi/blob/master/extension/src/main/java/org/axonframework/cdi/messaging/annotation/CdiParameterResolverFactory.java) and [**DefaultParameterResolverFactory**](https://github.com/AxonFramework/AxonFramework/blob/31fe8a7eae7bf019b7e7e4fc10d5ee2230e0b56b/messaging/src/main/java/org/axonframework/messaging/annotation/DefaultParameterResolverFactory.java), for example, has the same value of **Priority.LOW**.

If you check the [**PriorityAnnotationComparator**](https://github.com/AxonFramework/AxonFramework/blob/31fe8a7eae7bf019b7e7e4fc10d5ee2230e0b56b/messaging/src/main/java/org/axonframework/common/annotation/PriorityAnnotationComparator.java) and [**MultiParameterResolverFactory**](https://github.com/AxonFramework/AxonFramework/blob/31fe8a7eae7bf019b7e7e4fc10d5ee2230e0b56b/messaging/src/main/java/org/axonframework/messaging/annotation/MultiParameterResolverFactory.java) you will see that there is a comparison by priority value. In addition, when resolving **ParameterResolver** by calling **MultiParameterResolverFactory#createInstance**, it returns first not null **ParameterResolver**.

I might assume, that having multiple arguments (in command handler / event handler methods) and improper order of loading these factories and resolvers causes this issue. 

What do you think?

**Comment by bert-laverman** [comment]
Vladyslav,
having the same priority twice causes no problems, unless two or more ParameterResolverFactories want to handle the same type but in a different way. Then you don't know which gets called upon first. However, the priority is just for ordering the list, so two with the same prio will simply end up next to each other.

Bert

**Comment by vbaidak** [comment]
I'm not very sure about whether these factories are resolved correctly with having **CdiParameterResolverFactory**. In fact, we have a very complex application with custom parameter resolver factories and custom parameters, which are resolved when command handler / event handler methods are invoked. I shall check this more carefully soon, so for now we can close this discussion.

Another problem I found is that having a separate command handler (apart from handling commands directly in aggregate) also results in **NoHandlerForCommandException** exception. Can you confirm this?

**Comment by bert-laverman** [comment]
Vladyslav,
I understand that you are running more than just the jee example app, or at least not the default one.

As a test, I added a HelloCommand:
```Java
public class HelloCommand {

    private String msg;

    public HelloCommand() {
    }

    public HelloCommand(String msg) {
        this.msg = msg;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
}
```
and a standalone command handler:
```Java
@ApplicationScoped
public class StandAloneCommandHandler {

    private static final Logger logger = Logger.getLogger(MethodHandles.lookup().lookupClass().getName());

    @PostConstruct
    private void init() {
        logger.info("init()");
    }

    @PreDestroy
    private void shutdown() {
        logger.info("shutdown()");
    }

    @CommandHandler
    public String handle(HelloCommand hello) {
        logger.info("handle(): msg = \"" + hello.getMsg() + "\"");

        return "hi there!'";
    }
}
```

then, in the `AccountApplication` class, method `run()`, I added:
```Java
        Object reply = commandGateway.sendAndWait(new HelloCommand("Say peep!"));
        logger.info("run(): I got a " + reply.toString());
```

Running this in WildFly 14.0.1 I see in the logs:
```
08:37:24,005 INFO  [org.axonframework.cdi.example.javaee.AccountApplication] (ServerService Thread Pool -- 72) Initializing Account application.
08:37:24,024 INFO  [org.axonframework.cdi.example.javaee.command.Account] (ServerService Thread Pool -- 72) Handling: Create Account Command with accountId=6757a85d-f8c9-4775-ba1a-e27dee3ad759, overdraftLimit=100.0.
08:37:24,027 INFO  [org.axonframework.cdi.example.javaee.command.Account] (ServerService Thread Pool -- 72) Applying: Account Created Event with accountId=6757a85d-f8c9-4775-ba1a-e27dee3ad759, overdraftLimit=100.0.
08:37:24,036 INFO  [org.axonframework.eventhandling.interceptors.EventLoggingInterceptor] (ServerService Thread Pool -- 72) Events published: [AccountCreatedEvent] while processing a [CreateAccountCommand] which yielded a [GenericResultMessage] return value
08:37:24,060 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (EventProcessor[org.axonframework.cdi.example.javaee.query]-0) HHH000397: Using ASTQueryTranslatorFactory
08:37:24,135 INFO  [org.axonframework.cdi.example.javaee.command.StandAloneCommandHandler] (ServerService Thread Pool -- 72) handle(): msg = "Say peep!"
08:37:24,136 INFO  [org.axonframework.cdi.example.javaee.AccountApplication] (ServerService Thread Pool -- 72) run(): I got a hi there!'
```

So it works here.

Did you make the class with the `CommandHandler` a proper bean? Note I made my example `@ApplicationScoped`.

Cheers,
Bert

**Comment by vbaidak** [comment]
Yes, @bert-laverman , you're right! It wasn't a proper CDI bean.
And since it was not annotated, it wasn't picked up by AxonCdiExtension

Thanks for your time!
