### ISSUE TITLE
Test on WebSphere Liberty

### ISSUE THREAD

**Issue by m-reza-rahman** [AxonFramework/cdi#8]

**Comment by felipe-alves-moraes** [comment]
I can try to test those servers later today, if nobody picks it.

**Comment by m-reza-rahman** [comment]
You can go for it. You will need to setup a default data source for both the test and Cargo. You can pick embedded Derby or H2.

**Comment by felipe-alves-moraes** [comment]
I'm getting this output when I try to run on open liberty javaee8 version:
```[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering entity manager provider SimpleEntityManagerProvider.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering serializer JacksonSerializer.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering transaction manager JtaTransactionManager.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - No command bus producer found, using default simple command bus.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering event handler org.axonframework.cdi.example.javaee.query.GenericEventListener.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering event handler org.axonframework.cdi.example.javaee.query.AccountProjection.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering token store JpaTokenStore.
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.Dom4JToByteArrayConverter] is ignored. It seems to rely on a class that is not available in the class loader: org/dom4j/Document
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.InputStreamToDom4jConverter] is ignored. It seems to rely on a class that is not available in the class loader: org/dom4j/Document
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.XomToStringConverter] is ignored. It seems to rely on a class that is not available in the class loader: nu/xom/Document
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.InputStreamToXomConverter] is ignored. It seems to rely on a class that is not available in the class loader: nu/xom/ParsingException
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.Dom4JToByteArrayConverter] is ignored. It seems to rely on a class that is not available in the class loader: org/dom4j/Document
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.InputStreamToDom4jConverter] is ignored. It seems to rely on a class that is not available in the class loader: org/dom4j/Document
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.XomToStringConverter] is ignored. It seems to rely on a class that is not available in the class loader: nu/xom/Document
[err] [Default Executor-thread-289] INFO org.axonframework.serialization.ChainingConverter - ContentTypeConverter of type [class org.axonframework.serialization.xml.InputStreamToXomConverter] is ignored. It seems to rely on a class that is not available in the class loader: nu/xom/ParsingException
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering event storage JpaEventStorageEngine.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Starting Axon configuration.
[err] [Default Executor-thread-289] WARN org.axonframework.cdi.messaging.annotation.CdiParameterResolverFactory - Ambiguous reference for parameter type java.lang.Object with qualifiers [].
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Registering Axon APIs with CDI.
[err] [Default Executor-thread-289] INFO org.axonframework.cdi.AxonCdiExtension - Axon Framework configuration complete.
[ERROR   ] CWWKZ0004E: An exception occurred while starting the application javaee-axon-example-0.1-SNAPSHOT. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type EventBus with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.axonframework.cdi.example.javaee.AccountApplication.eventBus
  at org.axonframework.cdi.example.javaee.AccountApplication.eventBus(AccountApplication.java:0)
```

And this error when I try to run on open liberty full:
```A POST_CONSTRUCT lifecycle inteceptor threw an exception: org.axonframework.commandhandling.NoHandlerForCommandException: No handler was subscribed to command [org.axonframework.cdi.example.javaee.command.CreateAccountCommand]
        at org.axonframework.commandhandling.SimpleCommandBus.lambda$doDispatch$0(SimpleCommandBus.java:116)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.axonframework.commandhandling.SimpleCommandBus.doDispatch(SimpleCommandBus.java:114)
        at org.axonframework.commandhandling.SimpleCommandBus.dispatch(SimpleCommandBus.java:85)
        at org.axonframework.commandhandling.gateway.AbstractCommandGateway.send(AbstractCommandGateway.java:79)
        at org.axonframework.commandhandling.gateway.DefaultCommandGateway.send(DefaultCommandGateway.java:95)
        at org.axonframework.commandhandling.gateway.DefaultCommandGateway.send(DefaultCommandGateway.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at [internal classes]
        at org.axonframework.commandhandling.gateway.CommandGateway$863866205$Proxy$_$$_WeldClientProxy.send(Unknown Source)
        at org.axonframework.cdi.example.javaee.AccountApplication.run(AccountApplication.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ejs.container.interceptors.InterceptorProxy.invokeInterceptor(InterceptorProxy.java:205)
        at [internal classes]
```

**Comment by m-reza-rahman** [comment]
Thanks for giving this a spin. I'll take a look at this early next week. It's either a CDI bug or a bug in our code base. I may need to contact the Liberty team.
